### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by fergalom** [jschlyter/spc-web-gateway-docker#3]
Sorry, back again, note I have this working via an Rpi for >2yrs so trying to move to docker on another host.

Have changed the spc-gateway IP in SPC panel and config.xml and using same settings / EDP key
Using the docker-compose.yaml

Docker logs say:
No logs available

Using curl to test:
```
Command failed: curl -X GET http://192.168.1.4:8088/spc/area -k --digest -v
* Hostname was NOT found in DNS cache
*   Trying 192.168.1.4...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.1.4 (192.168.1.4) port 8088 (#0)
> GET /spc/area HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 192.168.1.4:8088
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 192.168.1.4 left intact
curl: (52) Empty reply from server
```

docker-compose.yaml (extract)
```
    spc-web-gateway:
        container_name: spc-gateway
        image: spc-web-gateway
        tty: true
        ports:
          - 8088:8088
          - 16000:16000
        volumes:
          - /opt/spc-web-gateway/auth:/opt/spc-web-gateway/auth:z
          - /opt/spc-web-gateway/config.xml:/opt/spc-web-gateway/config.xml:ro
        restart: unless-stopped
        network_mode: host
```

**Comment by RMarjanovic** [comment]
Hi fergalom, what have you changed in the SPC config?

What I can see in my SPC config, the only IP config setting is related to access control, which needs to match the same subnet as the computers trying to access SPC.

In my case I'm allowing all computers on subnet 192.168.9 to access SPC.

`<access_control_list>+192.168.9.0/24</access_control_list>`

I'm guessing that your running the curl command on the new host where you've installed the new instance of SPC? 

R

**Comment by fergalom** [comment]
Cheers, you tipped me off to something to re-examine. Changed from host, passed thru ports and added the docker network to the access list also as well as lan.
Worked

`<access_control_list>-0.0.0.0/0,+192.168.1.0/24,+172.19.0.0/24</access_control_list>`

**Comment by RMarjanovic** [comment]
Great, glad you got it to work!

R

**Comment by jschlyter** [comment]
Dito!
