### ISSUE TITLE
Unable to Docker Build spc-web-gateway

### ISSUE THREAD

**Issue by 1iveowl** [jschlyter/spc-web-gateway-docker#4]
Why do I get this error when trying to build the image?

> Step 17/22 : RUN sh $TEMP_DIR/install-spc-web-gateway.sh
>  ---> Running in 6300f57dde7b
> : not foundb-gateway-install/install-spc-web-gateway.sh: 2: /tmp/spc-web-gateway-install/install-spc-web-gateway.sh:
> : not foundb-gateway-install/install-spc-web-gateway.sh: 5: /tmp/spc-web-gateway-install/install-spc-web-gateway.sh:
> : not foundb-gateway-install/install-spc-web-gateway.sh: 11: /tmp/spc-web-gateway-install/install-spc-web-gateway.sh:
> : not foundb-gateway-install/install-spc-web-gateway.sh: 19: /tmp/spc-web-gateway-install/install-spc-web-gateway.sh:
> : not foundb-gateway-install/install-spc-web-gateway.sh: 22: /tmp/spc-web-gateway-install/install-spc-web-gateway.sh:
> req: Unknown digest nodes
> req: Use -help for summary.
> chgrp: cannot access '/opt/spc-web-gateway'$'\r''/auth/ssl_certificate.pem'$'\r\r': No such file or directory
> chmod: cannot access '/opt/spc-web-gateway'$'\r''/auth/ssl_certificate.pem'$'\r\r': No such file or directory

**Comment by RMarjanovic** [comment]
Have you added the install files etc as received by Lundix in the same folder as the files in this repository before building? The repository doesn’t come with all files needed to build an image.

**Comment by 1iveowl** [comment]
I've tried merging the two folders and I've tried placing this repo one level above "spc-web-gateway-1-3". 

The latter seems to be the right ways as the Dockerfile assumes that the files are in "spc-web-gateway-1.3" as per line 4:

`ARG SOURCE_DIR=spc-web-gateway-$VERSION`

**Comment by jschlyter** [comment]
Yes, the spc gateway directory (e.g., `spc-web-gateway-1.3`) must by in the same folder as the Dockerfile or Docker can not copy it inte the container.

**Comment by RMarjanovic** [comment]
I looked at my build from a few months ago and I'm using the standard
dockerfile from the repository.

Step 15/22 : COPY $SOURCE_DIR $TEMP_DIR/ ---> aab1a6d16ba7 Step 16/22 :
COPY install-spc-web-gateway.sh $TEMP_DIR/ ---> 433f3fa04102 Step 17/22 :
RUN sh $TEMP_DIR/install-spc-web-gateway.sh ---> Running in 54497f6ef5ac
The only thing I can think of with the information available is that it has
do something with the folder structure. Are you using the 1.3 version of
SPC (as well as the ubuntu version)? The Dockerfile contains a variable
"version" which directly effects the source directory of the installfile.

FROM ubuntu:16.04 ARG VERSION=1.3 ARG SOURCE_DIR=spc-web-gateway-$VERSION
ARG TEMP_DIR=/tmp/spc-web-gateway-install

I used the following structure when compiling
[image: image.png]

**Comment by RMarjanovic** [comment]
I looked at my build from a few months ago and I'm using the standard
dockerfile from the repository.

```
Step 15/22 : COPY $SOURCE_DIR $TEMP_DIR/ ---> aab1a6d16ba7 
Step 16/22 : COPY install-spc-web-gateway.sh $TEMP_DIR/ ---> 433f3fa04102 
Step 17/22 : RUN sh $TEMP_DIR/install-spc-web-gateway.sh ---> Running in 54497f6ef5ac
```

The only thing I can think of with the information available is that it hasto do something with the folder structure. Are you using the 1.3 version of SPC (as well as the ubuntu version)? 

The Dockerfile contains a variable "version" which directly effects the source directory of the installfile.

```
FROM ubuntu:16.04
ARG VERSION=1.3 
ARG SOURCE_DIR=spc-web-gateway-$VERSION
ARG TEMP_DIR=/tmp/spc-web-gateway-install
```

I used the following structure when compiling
![skarmklipp](https://user-images.githubusercontent.com/39992290/47909573-9e762580-de90-11e8-9e9d-5b95caa178d4.JPG)

**Comment by 1iveowl** [comment]
The above depiction is exactly how I did it too.

Could it be because I try to build the image on a Windows machine? The plan is to run it on Ubuntu, but I was trying to build on Windows. I didn't think it made a difference as Docker on Windows runs the container inside a Linux host. Docker is of course configure for Linux and not Windows.

**Comment by RMarjanovic** [comment]
I myself had problems with using Windows to compile. Never got it to work. 

If you don't want to try compiling in an linux enviroment, you could make a private repository in GitHub with webhooks to a private repository in DockerHUB.

By adding all files to the private repository in GitHUB, it should autocompile into a Docker file which you can pull from DockerHUB. 

This is the way I did to make it work.

**Comment by 1iveowl** [comment]
Thank you. I will try that.

**Comment by 1iveowl** [comment]
Thank you. That worked. Also, I changed the first line of the Dockerfile to Ubuntu 18.4. 

I can now pull from my own dockerhub image. Check 👍 

I  changed the docker-compose file to the name of my private personal image at dockerhub. Also, I had another spc-web-gateway running on a RPi, so I copied the configuration from this functional instance to /etc/spc-web-gateway folder on the Ubuntu server (18.04) that I want to run spc-web-gateway on going forward. 

Unfortunately, I get this error when running `docker-compose up`: 

> [username]:~/spc-web-gateway$ docker-compose up
> Creating spc-web-gateway_gateway_1 ... done
> Attaching to spc-web-gateway_gateway_1
> gateway_1  | spc-web-gateway: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> spc-web-gateway_gateway_1 exited with code 127 

So, should I add and `apt install` to the Dockerfile to make sure that `libcrypto.so.1.0.0` is available in the image?

**Comment by 1iveowl** [comment]
The issue seems not to be there if building for Ubuntu 16.4.

**Comment by jschlyter** [comment]
spc-gw does not support the OpenSSL provided in Ubuntu 18.04.

**Comment by spiffzilla** [comment]
Anyone heard from the developer of spc-gw if it will in next release?

**Comment by jschlyter** [comment]
We can ask @Goran58. I only know of version 1.3 built for:

- Debian 8 on armhf (armv7l)
- Debian 9 on armhf (armv7l)
- Ubuntu 16.04 x86 (x86_64)

Releases for Debian 10 / modern Ubuntu would be most useful. I've also asked @Goran58 to provide public downloads (sans license file of course) so we can implement a build chain and push images to Docker hub or the like.
