### ISSUE TITLE
libcrypto missing

### ISSUE THREAD

**Issue by spiffzilla** [jschlyter/spc-web-gateway-docker#5]
Hi
All reqs. fulfilled, but i get this on a Debian 10, any ideas?

> root@08f7450287f4:/opt/spc-web-gateway# ./bootstrap.sh
Generating a RSA private key
........+++++
......................................................................................................................
...................................+++++
writing new private key to '/opt/spc-web-gateway/auth/ssl_certificate.pem'
>-----
>./spc-web-gateway: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared >object file: No such file or directory
>root@08f7450287f4:/opt/spc-web-gateway#
>

**Comment by jschlyter** [comment]
Are you building the container using the Dockerfile? Only the `ubuntu:16.04` image is supported by spc-web-gateway unless @Goran58 has updated the dependencies.

**Comment by jschlyter** [comment]
See #4 for solutions.
