### ISSUE TITLE
docker-compose file error

### ISSUE THREAD

**Issue by Simonk007** [jschlyter/spc-web-gateway-docker#7]
Hi,
im kinda newbie in docker, i have tried using you docker-compose file in my own docker setup.
I have done as followed:
1. create a new folder: /opt/spec-web-gateway
2.  create docker-compose.yml with the following config
version: '2'
services:
  gateway:
    image: spc-web-gateway
    tty: true
    ports:
      - "8088:8088"
      - "16000:16000"
    volumes:
      - etc/auth:/opt/spc-web-gateway/auth:z
      - etc/config.xml:/opt/spc-web-gateway/config.xml:ro
    restart: unless-stopped
    network_mode: host

3. Run docker-compose up - getting the following error:
- ERROR: Named volume "etc/auth:/opt/spc-web-gateway/auth:z" is used in service "gateway" but no declaration was found in the volumes section.

What am i doing wrong, hope someone can help get going. Take care

**Comment by Simonk007** [comment]
Found the error:)
How do i buy access for the gateway?

**Comment by jschlyter** [comment]
Talk to Göran at Lundix
